### ISSUE TITLE
Remove local

### ISSUE THREAD

**Issue by IanaKhitsko** [danya-psch/euro_diffusion#2]
https://github.com/danya-psch/euro_diffusion/blob/fd4b5f66dd90a9162ec5df8f4c807029de15094b/context.py#L22

Flag is useless. Just return the boolean value

**Comment by danya-psch** [comment]
No, it is a good practice to use one return statement in function

**Comment by IanaKhitsko** [comment]
Actually, it is not anymore. This is old style. The flag is really redundant here, please don't write the code in such way.

**Comment by danya-psch** [comment]
done
