### ISSUE TITLE
remove local

### ISSUE THREAD

**Issue by IanaKhitsko** [danya-psch/euro_diffusion#4]
https://github.com/danya-psch/euro_diffusion/blob/fd4b5f66dd90a9162ec5df8f4c807029de15094b/context.py#L65

Again. Don't use any flags, just return true/false

**Comment by danya-psch** [comment]
It is a good practice to use one return statement in function

**Comment by IanaKhitsko** [comment]
If you still use structural programming techniques - yes, according to https://en.wikipedia.org/wiki/Structured_programming.
If not - please see Martin Fawler work (Refactoring: Improving the Design of Existing Code) or you should visit my lectures where I am telling why it is not good. Or at least read the materials on last lectures which I will send today or tomorrow.

**Comment by danya-psch** [comment]
done
