### ISSUE TITLE
Acronyms

### ISSUE THREAD

**Issue by IanaKhitsko** [danya-psch/euro_diffusion#5]
https://github.com/danya-psch/euro_diffusion/blob/fd4b5f66dd90a9162ec5df8f4c807029de15094b/context.py#L86

Please don't use acronyms. Reading such code is a nightmare. c,s etc - please give normal name to be your code seld-documented

**Comment by danya-psch** [comment]
Which exact name you did not understand in this line of code?

**Comment by IanaKhitsko** [comment]
c-> country, s-> city?? sc -> city_coordinates??

**Comment by danya-psch** [comment]
done
