### ISSUE TITLE
Make the method more linear

### ISSUE THREAD

**Issue by IanaKhitsko** [danya-psch/euro_diffusion#6]
https://github.com/danya-psch/euro_diffusion/blob/fd4b5f66dd90a9162ec5df8f4c807029de15094b/context.py#L97-L98

if self.world is None 
   return True

Remove res. It is always == tc_complete, right?

**Comment by danya-psch** [comment]
It is a good practice to use one return statement in function, this increases code readability, when res variable takes only 28 bits
```
res = True
sys.getsizeof(res) == 28
```

**Comment by IanaKhitsko** [comment]
see https://refactoring.guru/replace-nested-conditional-with-guard-clauses or Martin Fawler's corresponding work on refactoring.

**Comment by danya-psch** [comment]
done
